services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-server
    volumes:
      - ./backend/logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    depends_on:
      - test # Ensure 'test' runs first

  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-test
    command: ["sh", "-c", "python manage.py test address && exit 0"]
    env_file:
      - .env
    restart: "no"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    restart: always
    depends_on:
      - test # Ensure 'test' runs first
